# Generated by Django 4.2.7 on 2023-11-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publisher_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='Publisher',
        ),
    ]
